# Generated by Django 5.1.2 on 2024-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_language_word_delete_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
