# Generated by Django 5.1.2 on 2024-10-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_language_code_alter_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='No Translation', max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='lang_origin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
