# Generated by Django 5.1.2 on 2024-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_word_translation_alter_word_lang_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=50),
        ),
    ]
