# Generated by Django 5.1.2 on 2024-10-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_word_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
